// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sky_webapi.Data;

#nullable disable

namespace sky_webapi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250629090000_FixRoleSeeding")]
    partial class FixRoleSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This should match your current model state after the RestoreSeeding migration
            // Just a placeholder - EF will handle the actual model state
        }
    }
}
